# Generated by Django 3.1.4 on 2021-03-24 09:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 24, 9, 26, 55, 241063, tzinfo=utc)),
        ),
    ]
